# Site settings
title: Nima Sarang
description: Nima's personal website

# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: localhost:4000 # the base hostname & protocol for your site e.g. http://tanka.la


# User settings
username: Nima Sarang
user_description: Hi! I'm Nima, a senior year student of B.Sc. Computer Science at the Amirkabir University of Tech, Tehran. I am passionate about learning machine learning algorithms and deep learning models and I tend to code most of the things I learn. I have research experience in bioinformatics, particularly, protein design and evaluation. In my spare time, I tend to listen to music and play guitar, mostly classics :) I also take pleasure in mountain climbing.
user_title: Machine Learning Researcher
email: nimasarang@gmail.com



# if it's an external image, update below for true
# better with square images
external-image: false
picture: ./assets/img/profile.jpg


# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-url: assets/pdf/CV_Nima_May19.pdf






# Google-analytics
google-analytics:
  id: UA-141136428-1

exclude: ['package.json', 'src' , 'node_modules']
